### ISSUE TITLE
Package Names

### ISSUE THREAD

**Issue by michaelstaib** [cajuncoding/HotChocolate.RepoDb#1]
hey,

could you please use not the HotChocolate.* names for your packages, this starts interfering with our own work and blocks us from extending the core framework. Moreover, it confuses users that want to consume packages from the core project.

we are in talks with the nuget team to block the packages but would like you to publish your packages under a different name.

Further, you can list your extensions with our project as community extensions so you get more traction.

**Comment by cajuncoding** [comment]
No problem, I understand! My apologies, I meant no interference, only to help them be identifiable.

I will change the names and pull the existing ones offline ASAP.

Thanks for understanding and letting me know!

**Comment by cajuncoding** [comment]
@michaelstaib I got this done as quickly as I could..... 

I've now Unlisted, and Deprecated all existing packages in Nuget.  I updated my Repo & Package names to simply use GraphQL prefix now and republished.  I hope this resolves any issues you may have experienced!  Thanks for the awesome work you all have done with HotChocolate!

**Comment by cajuncoding** [comment]
@michaelstaib let me know what I can do to get these listed as community extensions -- I think they may really help others out with similar use-cases.  Thanks :-)

**Comment by michaelstaib** [comment]
Thanks for your quick action on this...

do a PR here:
https://github.com/ChilliCream/hotchocolate/blob/main/COMMUNITY.md

we will also list them on the website and direct people to them once we have released version 11
