### ISSUE TITLE
How to view the schema?

### ISSUE THREAD

**Issue by ZedZipDev** [cajuncoding/HotChocolate.RepoDb#5]
I have built and run StarWars-AzureFunctions-RepoDB server , then run 
1. http://localhost:7071/api/graphql
{"errors":[{"message":"Either the parameter query or the parameter id has to be set.","extensions":{"code":"HC0013"}}]}

2. http://localhost:7071/api/graphql/playground/
No any schema. How to view the schema and run a query?

**Comment by cajuncoding** [comment]
@Oleg26Dev 

1. In question number 1, if you are seeing that error `Either the parameter query or the parameter id has to be set.`, I can only assume that is in the browser window (since you didn't submit any screenshot or context).  That means that you are using that endpoint incorrectly.  
    - The `/api/graphql` endpoint is the query engine and is not a valid web uri.  It's telling you that you have not provided the parameter named `query` which is required in order to execute it.  
    - Therefore to use that in the browser you must provide a a well formed, encoded, graphql query in the query string because the browser will only use a GET request.  And, generally that's not what you'd want to use as you'll likely want to use a POST request and a valid GraphQL client or IDE as below...
    - ![image](https://user-images.githubusercontent.com/20844814/126533214-e66ecea4-6343-452c-8048-6f3f8429e308.png)

2. To view the Schema and/or run a query you should use a GraphQL IDE... HotChocolate provides a built in IDE named "Banana Cake Pop" that is available on the endpoint `/api/graphql/playground`.
    - That is the url you should enter into a browser and it will load the IDE.
    - Then it's very important that you check that the GraphQL engine API is correct which must be set to the endpoint `/api/graphql' in the tab inside of Banana Cake Pop; by default it loads the url from the browser but that is different in my example due to how Azure Functions must work.
    - ![image](https://user-images.githubusercontent.com/20844814/126533964-c30d7d2a-74ea-4c7e-b5bf-2964b04d788f.png)

3. Finally, per your question about the Schema, it's not clear if you were looking to browse it via the IDE (as shown above in number 2 above) or download the raw schema definition, which is also supported via HotChocolates query string param `?sdl` (a documented feature of HC):
    - ![image](https://user-images.githubusercontent.com/20844814/126534968-5f344677-705e-47fb-8c29-4eaed8038b91.png)

**Comment by Oleg26Dev** [comment]
You wrote:

> 2. To view the Schema and/or run a query you should use a GraphQL IDE... HotChocolate provides a built in IDE named "Banana Cake Pop" that is available on the endpoint /api/graphql/playground.

But I did this (see the 1st msg), it is the same?

http://localhost:7071/api/graphql/playground/

**Comment by ZedZipDev** [comment]
Thank you, I see, the matter is the Banana Cake Pop IDE substituted the same link to its Page Tab too, i.e. 
/api/graphql/playground
But the 2nd one should be
/api/graphql/
Now I see the schema.

**Comment by Oleg26Dev** [comment]
Now I can view the schema, all is ok. 
Yet another question.

Wwhen I run the query
```
query {
  allCharacters(order: { name: ASC }) {
      personalIdentifier
      name
  }
}

```

I even cannot reach the debug point in the VS here:
```
       [UseSorting]
        [GraphQLName("allCharacters")]
        public async Task<IEnumerable<ICharacter>> GetAllCharactersAsync(
            [Service] ICharacterRepository repository,
            [GraphQLParams] IParamsContext graphQLParams
        )
        {
            var repoDbParams = new GraphQLRepoDbMapper<CharacterDbModel>(graphQLParams);

            var sortedCharacters = await repository.GetAllSortedCharactersAsync(
                selectFields: repoDbParams.GetSelectFields(), 
                sortFields: repoDbParams.GetSortOrderFields()
            );

            return sortedCharacters.AsPreProcessedSortResults();
        }

```

What is wrong?
